// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckManager.InfraStructure;

namespace TruckManager.InfraStructure.Migrations
{
    [DbContext(typeof(TruckManagerContext))]
    partial class TruckManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TruckManager.Domain.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbTruck");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 18, 19, 33, 19, 555, DateTimeKind.Local).AddTicks(3394),
                            ManufactureYear = 2021,
                            ModelType = 1,
                            ModelYear = 2021,
                            Name = "Caminhão 01",
                            UpdatedAt = new DateTime(2021, 6, 18, 19, 33, 19, 556, DateTimeKind.Local).AddTicks(8730)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 18, 19, 33, 19, 557, DateTimeKind.Local).AddTicks(91),
                            ManufactureYear = 2021,
                            ModelType = 2,
                            ModelYear = 2021,
                            Name = "Caminhão 02",
                            UpdatedAt = new DateTime(2021, 6, 18, 19, 33, 19, 557, DateTimeKind.Local).AddTicks(125)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
